### ISSUE TITLE
Check if action is allowed before displaying the form

### ISSUE THREAD

**Issue by mauthi** [laravel-enso/FormBuilder#13]
Use case:
- I have entries in my table where no update is allowed (e.g. entries in last year)
- I disabled edit button in table already (there was a ticket a few weeks ago) - works fine
- Now I have the situation if anybody calls the edit url directly (enters it into address field in browser)
- form is display and updating is disabled (because I check this in backend) - but users are able to change date to current year and update the record
- to disable this I would like to show a toastr if the page is opened and redirect to overview

Like:
```
public function edit(Owner $owner, OwnerForm $form)
    {
        if ($owner.date = lastyear) {
            // show toastr "not allowed to edit"
            // return redirect to table 
        } else {
            return ['form' => $form->edit($owner)];
        }
    }
```
Do you have an idea?

**Comment by aocneanu** [comment]
It will be a longer discussion but hopefully a helpful one :)

Please clarify the first two bullets and then we'll move further.

> I have entries in my table where no update is allowed (e.g. entries in last year).

But you want the old entries to be visible in the table.
and
You also have entries from this year along with the old ones, that you want to be able to edit.

Is this correct?

> I disabled edit button in table already (there was a ticket a few weeks ago) - works fine

If the first two suppositions are true, this would not be a suitable solution because you would loose ability to edit the newer entries.

**Comment by mauthi** [comment]
1. correct

2. this works fine, I solved it with a custom button where I check date and if from this year I redirect to edit route

So with VueTable everything works fine, the only problem is if you manually call a url in browser with an id from last year

**Comment by aocneanu** [comment]
Ok, now I understand the workaround from bullet no 2, moving on. Some of the below may seem obvious, but it's better to state the obvious than to be misunderstood.

When the users click the `edit` button, they don't actually edit. They only see a form with the data they probably see in the table already. Normally you shouldn't have a problem showing the form with older entries. (so maybe you don't need the workaround with the custom button in the DT)

Next you need a custom logic in BE where you build the form object to specify that for entries "older than" the actions are limited to ... or none.

```
if ($oldEntry is old) {
    $form = (new Form($template)
           ...
       ->actions([''])
       ->edit($oldEntry);
}
```
I suppose this is what you are referring to when you say

>Now I have the situation if anybody calls the edit url directly (enters it into address field in browser)
form is display and updating is disabled (because I check this in backend)

but I don't understand

>but users are able to change date to current year and update the record.

How are they able to update the record if the `update` action is disabled?

And lastly, when you have users that intend to "hack" your app, and attempt to access records that they are not authorised to, their ergonomy should be the dev's last concern. You should check the permission in BE,  `throw new AuthorizationException()` or `throw new EnsoException('Your unauthorized attempt was reported to the app administrator')` and be done with it. Both exceptions should trigger a toaster already.

**Comment by mauthi** [comment]
> but I don't understand
>> but users are able to change date to current year and update the record.

The date of the record can be changed in the form. So the users opens an entry from last year (by manually inserting the url), changes date to this year and updates record. 
But if I think about this I should check in BE if old date was in last year and new date is in current year updating should not be possible.

> And lastly, when you have users that intend to "hack" your app, and attempt to access records that they are not authorised to, their ergonomy should be the dev's last concern. 
You are absolutely right!

Thx for your advise with the actions in Form Class - now it works.
