### ISSUE TITLE
Which actions are needed for create and update

### ISSUE THREAD

**Issue by mauthi** [laravel-enso/FormBuilder#14]
I have an object where create and update is possible but destroy is not allowed.
Which action do I need in form template json?
I tried two possibilites:

1) no actions provided in form template
- Create possible
- Update not possible - error: Route does not exist: management.customers.destroy

2) `"actions": ["create", "store", "update"]` or `"actions": ["create", "update"]`
- Create not possible - error: Missing required parameters for [Route: management.customers.update] [URI: api/management/customers/{customer}].
- Update possible

Is there an error or did I something wrong?

**Comment by mauthi** [comment]
sorry, forget this - solved it with your last comment in #13 (set the actions in FormClass and not in JSON)

**Comment by aocneanu** [comment]
I checked and the array in JSON works to.

`create`: stands for the create button, and can be used in an edit form, to open a new create form. It's useless in a create form.
`store`: can be used in a create form, not an edit one because if you edit a model you don't want to store it, but to update it
`update`: should be used only in an edit form, and it's dependent of the model's id
`destroy`: works only for existing models, so only in the edit form

**Comment by mauthi** [comment]
But if I use only on template for create and update I can’t set the correct values?

**Comment by aocneanu** [comment]
I don't know what you mean by
>But if I use only on template for create and update I can’t set the correct values?

But I can tell you that the actions are computed dynamically. If you set static values you override this behaviour, and you can have problems if you're trying to reuse the form for create / edit.
